MovieRecommendationSystem-main/Django files/MovieRecSystem/urls.py
from django.contrib import admin
from django.urls import path , include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('home.urls'))
]

MovieRecommendationSystem-main/Django files/home/urls.py
from django.contrib import admin
from django.urls import path

from home import views
urlpatterns = [
    
    path('' , views.homepage ,name='homepage'),
    path('about' , views.about ,name='about'),
    path('services' , views.services ,name='services'),


]

MovieRecommendationSystem-main/Django files/home/models.py
from django.db import models

# Create your models here.

MovieRecommendationSystem-main/Django files/home/forms.py
from email.policy import default
from tkinter import Widget
from django import forms

class Moviedata(forms.Form):
    movie =forms.CharField(label=("") ,widget=forms.TextInput(attrs={'class':'form-control',}))
    year = forms.IntegerField(label=(""),widget=forms.NumberInput(attrs={'class':'form-control',}))

    

MovieRecommendationSystem-main/Django files/home/views.py
from ast import arg
from lzma import MODE_FAST
import re
from django.shortcuts import render , HttpResponse
from home.forms import Moviedata
import requests



import pandas as pd
import numpy as np

# Create your views here.
def index(request):
    return HttpResponse("this is home app no url path woooh")

def about(request):
    return HttpResponse("this is about page")

def services(request):
    return HttpResponse("this is services page")


def fetch_poster(movieid):
    response =requests.get('https://api.themoviedb.org/3/movie/{}?api_key=b78a4c5a65cfebf5db59868a03e1a2db&language=en-US'.format(movieid))
    data =response.json()
    return  "https://image.tmdb.org/t/p/w200/" + data['poster_path']
def homepage(request):
    intial_data={
        'year':1916
    }
    if request.method=='POST':
        #data = Moviedata(request.POST)
        # if data.is_valid():
            # movie = data.cleaned_data['movie']
            # year = data.cleaned_data['year']
        movie=request.POST.get('movie')
        year=int(request.POST.get('year'))
        moviesdf =pd.read_csv('static\Final_MRS_DataSet.csv')
        moviesdf = moviesdf.drop('Unnamed: 0',axis=1)
        movie =movie.lower()
        moviesdf['title']=moviesdf['title'].str.lower()
        if(movie in moviesdf['title'].values):

            similarities = pd.read_csv('static\Similarites.csv')
            similarities =similarities.drop('Unnamed: 0',axis=1)

        
            
            # recommendation being done
            movie_index = moviesdf[moviesdf['title']==movie].index[0]
            dist = similarities.iloc[movie_index]
            recommendations =sorted(list(enumerate(dist)),reverse=True , key=lambda x:x[1])
            li =[]
            movie_posters=[]
        
            for j in range(1,len(moviesdf)):
                if(moviesdf.iloc[recommendations[j][0]]['release_data']>=year): # check the year if error
                    li.append(moviesdf.iloc[recommendations[j][0]])
                    
            
            li_rec=[]
            for i in li[0:5]:
                li_rec.append(i.title)
                #fetching poster from the movie
                movie_posters.append(fetch_poster(i.id))
            movies_dic = dict(zip(li_rec, movie_posters))


            args ={'Recommendations':movie_posters}
                
            
            return render(request ,'home1.html',args)    
        else:
            errorMessage="The movie you asked has not been found 😢😢 try another one!!"
            return render(request ,'base1.html',{'error':errorMessage})    






    else:
        # data = Moviedata(initial=intial_data)
    
        return render(request ,'base1.html')    




MovieRecommendationSystem-main/Django files/templates/base1.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Movie Recommendation System</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'home.css'%}">
  {% comment %} <style>
    
body{
  margin: 0;
  background-image: url('static/netflix.png');
  background-size: cover;
  
}
.nav_container ul {
    list-style-type: none;
    margin: 0;
    padding: 0;
    overflow: hidden;
    background-color: rgb(28, 27, 27);
    height: 5%;


  }
  
  .nav_container ul a{
    text-decoration: none;

  }
  li {
    float: left;
  }
  .nav_container h3{
    color: azure;
    margin-left: 5%;
    font-size:x-large;
  }
  li a {
    display: block;
    color: white;
    text-align: center;
    padding: 0px 10px 0px 16px;
    margin-left: 2000%;
    margin-top: -70%;
    text-decoration: none;
    font-weight:bold;
  }
  
  /* Change the link color to #111 (black) on hover */
  li a:hover {
    background-color: rgb(48, 48, 48);
    
  }
 .form_details #searchbtn{
    margin: 12% 35% 5% 0%;
    padding: 0.5% 3%;
    border-radius: 11px;
    background-color: rgb(198, 41, 41);
    color: rgb(3, 3, 3);
    font-size: large;
    font-weight: 200;
    border: black;


  }
  .form_details #searchbtn:hover{
    background-color: black;
    color: azure;
    cursor:pointer;
  
    }
  </style> {% endcomment %}

  </head>
  <body>
    <div class="containerbody">
      <header >
        <nav class="nav_container">
          <ul>
            <center><a href=""><h2 style='margin-right:6%;' class='glow'>Movie Recommendation System</h2></a></center>
            
          
    
          </ul>
        </nav> 
        </header>
        <div class="content_main">
           <center>  
                     <div >Bored and searching for a movie ??   </div>
                     <div>Tell us a movie you liked and I will give you suggestions</div>
          </center>
        </div>
        <div class="container">
            
            <div class='form_details'>
                <form class="d-flex" method="POST" role="search">
                    {% csrf_token %}
                    {{ form.as_p }}
                  
                <input type="text" name="movie" class="form-control" required id="id_movie" placeholder='Enter Movie'>
                <input type="number" name="year" value="1916" class="form-control" required id="id_year">
                <center><button class="btn btn-outline-success" type="submit" id="searchbtn">Recommend</button></center>
                </form>
          </div>
        </div>

        <div class="errorContainer">
          <center><div id='errortext'>{{error}}</div></center>
          
        </div>
        {% block body %}{% endblock body %}
        
    </div>
    
  </body>
</html>

MovieRecommendationSystem-main/Django files/templates/home1.html
{% extends 'base1.html' %}

{% block body %}

 <center><h2 style='color: rgb(255, 255, 0);'>These are the Top 5 Recommendations for you </h2></center>
{% comment %} <br>
<center>
    {% for key, value in Recommendations.items %} 
    <li>{{key}} -  <div class='movie_poster'><img src="{{value}}" alt="poster" ></div></li>
{% endfor %}
</center>   {% endcomment %}


<center>
    
    {% for movie in Recommendations %} 
    <li  style='margin: 2%;'><img src="{{movie}}" alt="poster" name="movie poster"></li>
{% endfor %}
</center>
{% endblock body %}